# Framework Environment Configurations
# Target environment: qa, uat, prod
env=qa

# Base URLs
qa.baseUrl=https://anvnacare.alwaysdata.net/
uat.baseUrl=https://anvnacare.alwaysdata.net/
prod.baseUrl=https://anvnacare.alwaysdata.net/

# Default User Credentials (QA)
qa.user.email=amit.kumar@anvnacare.com
qa.user.password=password123
qa.admin.email=admin@anvnacare.com
qa.admin.password=password123

# Default User Credentials (UAT)
uat.user.email=amit.kumar@anvnacare.com
uat.user.password=password123
uat.admin.email=admin@anvnacare.com
uat.admin.password=password123

# Default User Credentials (PROD)
prod.user.email=amit.kumar@anvnacare.com
prod.user.password=password123
prod.admin.email=admin@anvnacare.com
prod.admin.password=password123
